import type { Metadata } from 'next';
import './globals.css';
import { inter, plusJakartaSans } from '../../public/fonts/fonts';
import Header from '@/components/containers/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${plusJakartaSans.variable} flex flex-col items-center justify-center relative size-full overflow-x-hidden antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
