import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
// import { inter, plusJakartaSans } from '../../public/fonts/fonts';
// import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className=""
        // {`${inter.variable} ${plusJakartaSans.variable} font-plusJakartaSans flex flex-col items-center justify-center relative size-full overflow-x-hidden antialiased`}
      >
        {/* <Header /> */}
        <NavBar />
        <div className="pt-[100px] lg:pt-[140px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
